# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/Check-SNMP-plugins/Check-SNMP-plugins

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/Check-SNMP-plugins/Check-SNMP-plugins

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/Check-SNMP-plugins/Check-SNMP-plugins/CMakeFiles /home/runner/work/Check-SNMP-plugins/Check-SNMP-plugins//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/Check-SNMP-plugins/Check-SNMP-plugins/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named check_snmp_disk

# Build rule for target.
check_snmp_disk: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check_snmp_disk
.PHONY : check_snmp_disk

# fast build rule for target.
check_snmp_disk/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_disk.dir/build.make CMakeFiles/check_snmp_disk.dir/build
.PHONY : check_snmp_disk/fast

#=============================================================================
# Target rules for targets named check_snmp_process

# Build rule for target.
check_snmp_process: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check_snmp_process
.PHONY : check_snmp_process

# fast build rule for target.
check_snmp_process/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_process.dir/build.make CMakeFiles/check_snmp_process.dir/build
.PHONY : check_snmp_process/fast

#=============================================================================
# Target rules for targets named check_snmp_load

# Build rule for target.
check_snmp_load: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check_snmp_load
.PHONY : check_snmp_load

# fast build rule for target.
check_snmp_load/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_load.dir/build.make CMakeFiles/check_snmp_load.dir/build
.PHONY : check_snmp_load/fast

src/check_snmp_disk.o: src/check_snmp_disk.c.o
.PHONY : src/check_snmp_disk.o

# target to build an object file
src/check_snmp_disk.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_disk.dir/build.make CMakeFiles/check_snmp_disk.dir/src/check_snmp_disk.c.o
.PHONY : src/check_snmp_disk.c.o

src/check_snmp_disk.i: src/check_snmp_disk.c.i
.PHONY : src/check_snmp_disk.i

# target to preprocess a source file
src/check_snmp_disk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_disk.dir/build.make CMakeFiles/check_snmp_disk.dir/src/check_snmp_disk.c.i
.PHONY : src/check_snmp_disk.c.i

src/check_snmp_disk.s: src/check_snmp_disk.c.s
.PHONY : src/check_snmp_disk.s

# target to generate assembly for a file
src/check_snmp_disk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_disk.dir/build.make CMakeFiles/check_snmp_disk.dir/src/check_snmp_disk.c.s
.PHONY : src/check_snmp_disk.c.s

src/check_snmp_load.o: src/check_snmp_load.c.o
.PHONY : src/check_snmp_load.o

# target to build an object file
src/check_snmp_load.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_load.dir/build.make CMakeFiles/check_snmp_load.dir/src/check_snmp_load.c.o
.PHONY : src/check_snmp_load.c.o

src/check_snmp_load.i: src/check_snmp_load.c.i
.PHONY : src/check_snmp_load.i

# target to preprocess a source file
src/check_snmp_load.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_load.dir/build.make CMakeFiles/check_snmp_load.dir/src/check_snmp_load.c.i
.PHONY : src/check_snmp_load.c.i

src/check_snmp_load.s: src/check_snmp_load.c.s
.PHONY : src/check_snmp_load.s

# target to generate assembly for a file
src/check_snmp_load.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_load.dir/build.make CMakeFiles/check_snmp_load.dir/src/check_snmp_load.c.s
.PHONY : src/check_snmp_load.c.s

src/check_snmp_process.o: src/check_snmp_process.c.o
.PHONY : src/check_snmp_process.o

# target to build an object file
src/check_snmp_process.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_process.dir/build.make CMakeFiles/check_snmp_process.dir/src/check_snmp_process.c.o
.PHONY : src/check_snmp_process.c.o

src/check_snmp_process.i: src/check_snmp_process.c.i
.PHONY : src/check_snmp_process.i

# target to preprocess a source file
src/check_snmp_process.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_process.dir/build.make CMakeFiles/check_snmp_process.dir/src/check_snmp_process.c.i
.PHONY : src/check_snmp_process.c.i

src/check_snmp_process.s: src/check_snmp_process.c.s
.PHONY : src/check_snmp_process.s

# target to generate assembly for a file
src/check_snmp_process.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_process.dir/build.make CMakeFiles/check_snmp_process.dir/src/check_snmp_process.c.s
.PHONY : src/check_snmp_process.c.s

src/snmp-common.o: src/snmp-common.c.o
.PHONY : src/snmp-common.o

# target to build an object file
src/snmp-common.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_disk.dir/build.make CMakeFiles/check_snmp_disk.dir/src/snmp-common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_process.dir/build.make CMakeFiles/check_snmp_process.dir/src/snmp-common.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_load.dir/build.make CMakeFiles/check_snmp_load.dir/src/snmp-common.c.o
.PHONY : src/snmp-common.c.o

src/snmp-common.i: src/snmp-common.c.i
.PHONY : src/snmp-common.i

# target to preprocess a source file
src/snmp-common.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_disk.dir/build.make CMakeFiles/check_snmp_disk.dir/src/snmp-common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_process.dir/build.make CMakeFiles/check_snmp_process.dir/src/snmp-common.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_load.dir/build.make CMakeFiles/check_snmp_load.dir/src/snmp-common.c.i
.PHONY : src/snmp-common.c.i

src/snmp-common.s: src/snmp-common.c.s
.PHONY : src/snmp-common.s

# target to generate assembly for a file
src/snmp-common.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_disk.dir/build.make CMakeFiles/check_snmp_disk.dir/src/snmp-common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_process.dir/build.make CMakeFiles/check_snmp_process.dir/src/snmp-common.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check_snmp_load.dir/build.make CMakeFiles/check_snmp_load.dir/src/snmp-common.c.s
.PHONY : src/snmp-common.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... check_snmp_disk"
	@echo "... check_snmp_load"
	@echo "... check_snmp_process"
	@echo "... src/check_snmp_disk.o"
	@echo "... src/check_snmp_disk.i"
	@echo "... src/check_snmp_disk.s"
	@echo "... src/check_snmp_load.o"
	@echo "... src/check_snmp_load.i"
	@echo "... src/check_snmp_load.s"
	@echo "... src/check_snmp_process.o"
	@echo "... src/check_snmp_process.i"
	@echo "... src/check_snmp_process.s"
	@echo "... src/snmp-common.o"
	@echo "... src/snmp-common.i"
	@echo "... src/snmp-common.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

